### PR TITLE
feat: retry RTSP stream on RTCP BYE

### PR DESCRIPTION
**Pull request by Tigge**
When the `autoRetry` flag has been set `Player` will retry the
connection automatically on RTCP Bye.

If you implement your own player on top of `PlaybackArea` you can add
this behavior yourself by sending in an `onRtcp` prop:

```ts
const onRtcp = (msg: Rtcp) => {
  if (isRtcpBye(msg)) {
    // Refresh stream here
  }
}
```

### CODE REVIEW

**Review by barnomasoz — APPROVED** [review]
LGTM

**Review by lekoaf — CHANGES_REQUESTED** [review]
Should this not also be implemented in MediaStreamPlayer.tsx?

And documented in the readme.

**Comment by barnomasoz** [comment]
> Should this not also be implemented in MediaStreamPlayer.tsx?
> 
> And documented in the readme.

That's true, I agree. Have missed those parts while reviewing..

**Comment by Tigge** [comment]
> Should this not also be implemented in MediaStreamPlayer.tsx?
> 
> And documented in the readme.

Sounds reasonable. Done!

**Review by lekoaf — APPROVED** [review]
LGTM

**Pull request merged**
