### PR TITLE
feat: multi stream example

### PR DESCRIPTION
**Pull request by lekoaf**
Added an example to show that you can use multiple players showing different streams in a single page.

Also refactored the example page to be able to switch between single stream and multi stream examples.

Preview:
multistream1

### CODE REVIEW

**Comment by cubecleveland** [comment]
Thanks so much. The first example with the singles feed worked amazing!!
I was able to geta  single feed on a player form an Axis camera.

I am not using React so i simply just used Vanialla JS to call the componnet...
So the React code is a bit confusing too me....

I am going to try and embed the multi feed in Vanilla JS.
Should i just call the componenet multiple times with different host names or is there anything that needs to be done with the socket ?

Roy

**Comment by lekoaf** [comment]
> Should i just call the componenet multiple times with different host names or is there anything that needs to be done with the socket

Nope, that should probably work. Good luck. :smiley: 

If you have any other questions, feel free to ask. We are fairly good at React here, so if you need any help with that...

**Comment by lekoaf** [comment]
@cubecleveland In theory you could do something like this:

```html
<script src="media-stream-player.min.js"></script>

<media-stream-player hostname="192.168.0.90" />
<media-stream-player hostname="192.168.0.91" />
<media-stream-player hostname="192.168.0.92" />
<media-stream-player hostname="192.168.0.93" />
```

But I haven't actually tested that.

**Comment by cubecleveland** [comment]
Many thanks for your support... 
will that be  ok to code pen my Vaniall JS so other people can use ? I can leave an active pen with my Vanilla JS imrovements.
Roy

**Comment by lekoaf** [comment]
> Many thanks for your support...
> will that be ok to code pen my Vaniall JS so other people can use ? I can leave an active pen with my Vanilla JS imrovements.
> Roy

Sure, why not. Lets see where it leads. :+1:

**Review by barnomasoz — APPROVED** [review]
Looks good

**Comment by lekoaf** [comment]
@cubecleveland did you manage to set up a code pen with your implementation?

**Comment by cubecleveland** [comment]
lekof,

im back working on this project after long break, and planning to put this into action and build a codepn with some demo cameras i have... can u repost the examlple.
Roy

**Comment by lekoaf** [comment]
@cubecleveland, I've made an example which can try to run here:
https://github.com/AxisCommunications/media-stream-player-js/blob/main/examples/react-app/MultiStream.jsx

**Comment by cubecleveland** [comment]
Wonderful...
I have  a question:
Is the feed limited to axis camera only... what if i have a 3rd party
camera that has an RTSP feed would that work as well ?


CUBE Workspace
Corporate: 6240 Som Center Rd #130
Solon, OH 44139
T: 216.245.9629

**Comment by lekoaf** [comment]
@cubecleveland, _this_ library is pretty much limited to just AXIS devices. If you have generic RTSP streams you want to show video from, you'll have to go the advanced route with [media-stream-library](https://github.com/AxisCommunications/media-stream-library-js) instead.

This is because this library utilizes APIs that probably only exists on an AXIS device. They _might_ be present on ONVIF devices but I haven't tested so don't quote me on that.

**Comment by lekoaf** [comment]
@cubecleveland for further discussions, please open up a new issue instead. Thanks!

**Comment by cubecleveland** [comment]
I will do that. This is a wonderful work you did. As previouslly discussed,
I am also will open a codepen with an open camera for Axis user to spin so
i will port forward it do u want me to open issue on that as well ?

Roy


CUBE Workspace
Corporate: 6240 Som Center Rd #130
Solon, OH 44139
T: 216.245.9629

**Comment by lekoaf** [comment]
@cubecleveland please do. I'm curious how you will solve that. :smiley:

**Pull request merged**
